spring.application.name=SalesDemoSpringJSP
# コンテキストルートの設定
server.servlet.context-path=/SalesDemoSpringJSP
# JSP用設定
spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
# ポート番号
server.port=8080
# セッションタイムアウト（動作確認用）
# server.servlet.session.timeout=60s


# JDBCドライバ
spring.datasource.driver-class-name=org.postgresql.Driver
# 接続先データベース
spring.datasource.url=jdbc:postgresql://localhost:5432/sales_db
# ログインユーザ_ユーザ名
spring.datasource.username=postgres
# ログインユーザ_パスワード
spring.datasource.password=postgres


## SQLログ出力
#logging.level.org.hibernate.SQL=debug
#
## バインドパラメータ出力
#logging.level.org.hibernate.orm.jdbc.bind=trace
#logging.level.org.hibernate.type.EnumType=trace